### ISSUE TITLE
Could you please tell me how much faster your impl is than libevent binary heap impl? Thanks

### ISSUE THREAD

**Issue by Kiddinglife** [wahern/timeout#18]

**Comment by wahern** [comment]
For all operations (install, delete, expiration) the hierarchical timing wheel is O(1), whereas min-heap is O(log(N)), though I think on average inserts in min-heap might be O(1). Install and delete only involve a single double-linked-list operation and a single bit-wise integer operation. IOW, incredibly fast. However, expiration requires a timeout to cascade. It's conceptually O(1) because each timeout must only cascade down a fixed number of wheels irrespective of the number of installed timeouts. But in degenerate cases when timeout values are so large that they must cascade through many wheels, this can be a high fixed cost relative to min-heap, and so min-heap can outperform in practice. Each wheel can have a maximum of 64 slots, so each wheel can account for 6 bits of the timeout value. A hierarchical wheel with a depth of 4 wheels can represent 24 bits of a timeout. For typical network daemons that handles timeouts on the order of seconds or minutes and with a granularity of milliseconds, 24 bits is more than enough, even if all your timeouts are expiring instead of being deleted and re-added. If the granularity is higher (e.g. nanoseconds), the fixed cost is higher. If you're actually resolving timeouts at that resolution, the fixed cost is very high.

My benchmark code under bench/ actually exhibits this degenerate behavior for the expire tests because 1) I generate timeouts values using the libc routine random() that is 2) usually greater than the 24 bits representable by the default wheel parameters, and 3) I use an abstract clock (incrementing a simple variable a small amount), not the system clock, and so update the wheel in smaller increments than what would happen in a real server. So in my benchmarking scripts, timeout.c performs a little worse than min-heap when expiring all timeouts. It's still O(1) but timeout.c wouldn't out-perform until the number of timeouts hit the millions or billions. I need to rerun my benchmarks with smaller timeouts values and/or deeper wheels (WHEEL_NUM > 4), but haven't had time.

In general timeout.c should be no worse than min-heap, but almost always significantly faster in practice, on the order of 2x-3x faster when dealing with tens of thousands of timeouts. The benchmarking code is in the project tree--the make target is "bench-all". It depends on Lua and gnuplot.

**Comment by Kiddinglife** [comment]
Thank you for your detailed reply !
