### ISSUE TITLE
look like kind of bug...

### ISSUE THREAD

**Issue by Kiddinglife** [wahern/timeout#20]
my input:
    struct rand_cfg cfg1 =
    {
    /_min_timeout_/1,
    /_max_timeout_/381,
    /_start_at_/100,
    /_end_at_/1000,
    /_n_timeouts_/1,
    /_max_step_/10,
    /_relative_/0,
    /_try_removing_/0,
    /_finalize_/2 };
    DO_N(1, check_randomized(&cfg1))

my test result (more logs added):

....---------------init and add all sample timers ---------------
add_timer(pending)::abstimout=248,currtime 100,rem 148,

---------------filter out all expired timers ---------------

---------------now we test pending timers---------------
update(curtime 130)::a pending timer(abs_expires 248) got expired 
add_timer(pending)::abstimout=248,currtime 130,rem 118,
update(curtime 200)::a pending timer(abs_expires 248) got expired
add_timer(pending)::abstimout=248,currtime 200,rem 48,
update(curtime 250)::a pending timer(abs_expires 248) got expired
add_timer(expired)::abstimout=248,currtime 250,rem 15),

OK

problem is thetimer with absolute timeout 248 is should not be expired with current time 130, but it actually expired. 

why the whole tests passed by is because in times_update() functions calls timeouts_sche() but timeouts_sche() function internally will try to remove existing timer before adding it.

**Comment by Kiddinglife** [comment]
after dived into source codes, i found some thing wired in fuction tomeouts_int():

```
    if (T->pending[wheel])
    {
        slot = WHEEL_MASK & (T->curtime >> (wheel * WHEEL_BIT));

        /* ctz input cannot be zero: T->pending[wheel] is
         * nonzero, so rotr() is nonzero. */

        _timeout = (ctz(rotr(T->pending[wheel], slot)) + !!wheel)
                << (wheel * WHEEL_BIT);
        /* +1 to higher order wheels as those timeouts are one rotation in the future (otherwise they'd be on a lower wheel or expired) */

        _timeout -= relmask & T->curtime;
        /* reduce by how much lower wheels have progressed */

        timeout = MIN(_timeout, timeout);
    }
```

assume that
the cur time is 100 jiffies, represented as common clock  0:0:1:36 (1 multiply 64+36 = 100)
the timer with abs time out 248 jiffies,  represented as common clock  0:0:3:56 (3 multiply 64+56 = 248)
this timer's relative time out will be 248 - 100 = 148 jiffies,  represented as common clock  0:0:2:20 (2 multiply64+20 = 148).

we know:
_timeout will be assigned with relative jiffies of 128 on wheel 1, then it should be added with the rest jiffies on wheel 0, which should be 20 jiffies. 
However, in your impl,  it is actually subtracted with curr time's jiffies on wheel 0, which is 36 here.

this is what was observed when I debug your codes. plz tell me if i got wrong here. thanks.

**Comment by wahern** [comment]
This is difficult for me to explain because I have yet to rigorously analyze and document the algorithm. What you're seeing is a quirk that I allude to in the comment,

``` text
/*
 * TODO: It's likely that at least one of the
 * following three bit fill operations is redundant
 * or can be replaced with a simpler operation.
 */
```

When a wheel rolls over, we need to force a tick of the next higher wheel. The current code actually selects _two_ slots in the higher wheel to expire. It does this (IIRC) because it was the only way I could get it to work when the pending set for a wheel wraps around the edge of the bitfield, or something to that effect. And (my memory is _very_ fuzzy on this), I think that's because in some cases (several small increments?) we can't know for sure whether we processed the trailing slot on the previous update.

If you print out the pending bitfield in timeouts_update (using the bin64 macro in timeout-debug.h) you'll see what's happening,

``` text
# timeouts_update(tos, 100)
wheel[0] 1111111111111111111111111111111111111111111111111111111111111111
wheel[1] 0000000000000000000000000000000000000000000000000000000000000011

# timeouts_update(tos, 130)
wheel[0] 1111111111111111111111111111000000000000000000000000000000000111
wheel[1] 0000000000000000000000000000000000000000000000000000000000000011

# timeouts_update(tos, 200)
wheel[0] 1111111111111111111111111111111111111111111111111111111111111111
wheel[1] 0000000000000000000000000000000000000000000000000000000000001100
```

The 248 timeout is in wheel 1 slot 2, and you can see that slot 2 being processed twice--once for the update(130), and again for the update (200). Update 200 is when it actually cascades to the lower wheel.

I don't think it effects the Big-O complexity, but it is a quirk that someday I'd like to sit down and work through. I need to prove whether the duplicative work is fundamentally necessary, or is mitigating a problem in my bit field manipulation code.

**Comment by Kiddinglife** [comment]
thank you so much!
